req DELETE "/Authors/Delete?id=$(aid 1)"
expect "author with credited books survives a delete" "$(sql "SELECT COUNT(*) FROM Authors WHERE LastName='Marsh'")" "1"
req DELETE "/Books/Delete?id=$(bid 1)"
expect "book with credited authors survives a delete" "$(sql "SELECT COUNT(*) FROM Books WHERE Title='The Glass Meridian'")" "1"

req DELETE "/Authors/Delete?id=$(aid 11)"
expect "author with no books is deleted" "$(sql "SELECT COUNT(*) FROM Authors WHERE LastName='Kemp'")" "0"
req DELETE "/Books/Delete?id=$(bid 12)"
expect "book with no authors is deleted" "$(sql "SELECT COUNT(*) FROM Books WHERE Title='Unwritten Kingdoms'")" "0"
req DELETE "/Books/Delete?id=$(bid 12)"
expect "the same delete again changes nothing further" "$(sql "SELECT COUNT(*) FROM Books")" "12"
